// Code generated by gen-api-types. DO NOT EDIT.
package workflowartifactgctask

// WorkflowArtifactGCTask specifies the Artifacts that need to be deleted as well as the
// status of deletion
type Types struct {
	// APIVersion defines the versioned schema of this representation of an object.
	// Servers should convert recognized schemas to the latest internal value, and
	// may reject unrecognized values.
	// More info:
	// https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`
	// Kind is a string value representing the REST resource this object represents.
	// Servers may infer this from the endpoint the client submits requests to.
	// Cannot be updated.
	// In CamelCase.
	// More info:
	// https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string                `json:"kind,omitempty"`
	Metadata map[string]interface{} `json:"metadata"`
	// ArtifactGCSpec specifies the Artifacts that need to be deleted.
	// All nested field descriptions have been dropped due to Kubernetes size limitations.
	Spec Spec `json:"spec"`
	// ArtifactGCStatus describes the result of the deletion
	Status *Status `json:"status,omitempty"`
}

// ArtifactGCSpec specifies the Artifacts that need to be deleted.
// All nested field descriptions have been dropped due to Kubernetes size limitations.
type Spec struct {
	ArtifactsByNode map[string]ArtifactsByNode `json:"artifactsByNode,omitempty"`
}

type ArtifactsByNode struct {
	ArchiveLocation *ArchiveLocation    `json:"archiveLocation,omitempty"`
	Artifacts       map[string]Artifact `json:"artifacts,omitempty"`
}

type ArchiveLocation struct {
	ArchiveLogs *bool                       `json:"archiveLogs,omitempty"`
	Artifactory *ArchiveLocationArtifactory `json:"artifactory,omitempty"`
	Azure       *ArchiveLocationAzure       `json:"azure,omitempty"`
	Gcs         *ArchiveLocationGcs         `json:"gcs,omitempty"`
	Git         *ArchiveLocationGit         `json:"git,omitempty"`
	Hdfs        *ArchiveLocationHdfs        `json:"hdfs,omitempty"`
	HTTP        *ArchiveLocationHTTP        `json:"http,omitempty"`
	OSS         *ArchiveLocationOSS         `json:"oss,omitempty"`
	Plugin      *ArchiveLocationPlugin      `json:"plugin,omitempty"`
	Raw         *ArchiveLocationRaw         `json:"raw,omitempty"`
	S3          *ArchiveLocationS3          `json:"s3,omitempty"`
}

type ArchiveLocationArtifactory struct {
	PasswordSecret *PurplePasswordSecret `json:"passwordSecret,omitempty"`
	URL            string                `json:"url"`
	UsernameSecret *PurpleUsernameSecret `json:"usernameSecret,omitempty"`
}

type PurplePasswordSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type PurpleUsernameSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type ArchiveLocationAzure struct {
	AccountKeySecret *PurpleAccountKeySecret `json:"accountKeySecret,omitempty"`
	Blob             string                  `json:"blob"`
	Container        string                  `json:"container"`
	Endpoint         string                  `json:"endpoint"`
	UseSDKCreds      *bool                   `json:"useSDKCreds,omitempty"`
}

type PurpleAccountKeySecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type ArchiveLocationGcs struct {
	Bucket                  *string                        `json:"bucket,omitempty"`
	Key                     string                         `json:"key"`
	ServiceAccountKeySecret *PurpleServiceAccountKeySecret `json:"serviceAccountKeySecret,omitempty"`
}

type PurpleServiceAccountKeySecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type ArchiveLocationGit struct {
	Branch                *string                    `json:"branch,omitempty"`
	Depth                 *int64                     `json:"depth,omitempty"`
	DisableSubmodules     *bool                      `json:"disableSubmodules,omitempty"`
	Fetch                 []string                   `json:"fetch,omitempty"`
	InsecureIgnoreHostKey *bool                      `json:"insecureIgnoreHostKey,omitempty"`
	InsecureSkipTLS       *bool                      `json:"insecureSkipTLS,omitempty"`
	PasswordSecret        *FluffyPasswordSecret      `json:"passwordSecret,omitempty"`
	Repo                  string                     `json:"repo"`
	Revision              *string                    `json:"revision,omitempty"`
	SingleBranch          *bool                      `json:"singleBranch,omitempty"`
	SSHPrivateKeySecret   *PurpleSSHPrivateKeySecret `json:"sshPrivateKeySecret,omitempty"`
	UsernameSecret        *FluffyUsernameSecret      `json:"usernameSecret,omitempty"`
}

type FluffyPasswordSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type PurpleSSHPrivateKeySecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type FluffyUsernameSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type ArchiveLocationHTTP struct {
	Auth    *PurpleAuth    `json:"auth,omitempty"`
	Headers []PurpleHeader `json:"headers,omitempty"`
	URL     string         `json:"url"`
}

type PurpleAuth struct {
	BasicAuth  *PurpleBasicAuth  `json:"basicAuth,omitempty"`
	ClientCERT *PurpleClientCERT `json:"clientCert,omitempty"`
	Oauth2     *PurpleOauth2     `json:"oauth2,omitempty"`
}

type PurpleBasicAuth struct {
	PasswordSecret *TentacledPasswordSecret `json:"passwordSecret,omitempty"`
	UsernameSecret *TentacledUsernameSecret `json:"usernameSecret,omitempty"`
}

type TentacledPasswordSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type TentacledUsernameSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type PurpleClientCERT struct {
	ClientCERTSecret *PurpleClientCERTSecret `json:"clientCertSecret,omitempty"`
	ClientKeySecret  *PurpleClientKeySecret  `json:"clientKeySecret,omitempty"`
}

type PurpleClientCERTSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type PurpleClientKeySecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type PurpleOauth2 struct {
	ClientIDSecret     *PurpleClientIDSecret     `json:"clientIDSecret,omitempty"`
	ClientSecretSecret *PurpleClientSecretSecret `json:"clientSecretSecret,omitempty"`
	EndpointParams     []PurpleEndpointParam     `json:"endpointParams,omitempty"`
	Scopes             []string                  `json:"scopes,omitempty"`
	TokenURLSecret     *PurpleTokenURLSecret     `json:"tokenURLSecret,omitempty"`
}

type PurpleClientIDSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type PurpleClientSecretSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type PurpleEndpointParam struct {
	Key   string  `json:"key"`
	Value *string `json:"value,omitempty"`
}

type PurpleTokenURLSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type PurpleHeader struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type ArchiveLocationHdfs struct {
	Addresses               []string                  `json:"addresses,omitempty"`
	DataTransferProtection  *string                   `json:"dataTransferProtection,omitempty"`
	Force                   *bool                     `json:"force,omitempty"`
	HdfsUser                *string                   `json:"hdfsUser,omitempty"`
	KrbCCacheSecret         *PurpleKrbCCacheSecret    `json:"krbCCacheSecret,omitempty"`
	KrbConfigConfigMap      *PurpleKrbConfigConfigMap `json:"krbConfigConfigMap,omitempty"`
	KrbKeytabSecret         *PurpleKrbKeytabSecret    `json:"krbKeytabSecret,omitempty"`
	KrbRealm                *string                   `json:"krbRealm,omitempty"`
	KrbServicePrincipalName *string                   `json:"krbServicePrincipalName,omitempty"`
	KrbUsername             *string                   `json:"krbUsername,omitempty"`
	Path                    string                    `json:"path"`
}

type PurpleKrbCCacheSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type PurpleKrbConfigConfigMap struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type PurpleKrbKeytabSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type ArchiveLocationOSS struct {
	AccessKeySecret          *PurpleAccessKeySecret `json:"accessKeySecret,omitempty"`
	Bucket                   *string                `json:"bucket,omitempty"`
	CreateBucketIfNotPresent *bool                  `json:"createBucketIfNotPresent,omitempty"`
	Endpoint                 *string                `json:"endpoint,omitempty"`
	Key                      string                 `json:"key"`
	LifecycleRule            *PurpleLifecycleRule   `json:"lifecycleRule,omitempty"`
	SecretKeySecret          *PurpleSecretKeySecret `json:"secretKeySecret,omitempty"`
	SecurityToken            *string                `json:"securityToken,omitempty"`
	UseSDKCreds              *bool                  `json:"useSDKCreds,omitempty"`
}

type PurpleAccessKeySecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type PurpleLifecycleRule struct {
	MarkDeletionAfterDays         *int64 `json:"markDeletionAfterDays,omitempty"`
	MarkInfrequentAccessAfterDays *int64 `json:"markInfrequentAccessAfterDays,omitempty"`
}

type PurpleSecretKeySecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type ArchiveLocationPlugin struct {
	Configuration            *string `json:"configuration,omitempty"`
	ConnectionTimeoutSeconds *int64  `json:"connectionTimeoutSeconds,omitempty"`
	Key                      string  `json:"key"`
	Name                     *string `json:"name,omitempty"`
}

type ArchiveLocationRaw struct {
	Data string `json:"data"`
}

type ArchiveLocationS3 struct {
	AccessKeySecret          *FluffyAccessKeySecret          `json:"accessKeySecret,omitempty"`
	Bucket                   *string                         `json:"bucket,omitempty"`
	CASecret                 *PurpleCASecret                 `json:"caSecret,omitempty"`
	CreateBucketIfNotPresent *PurpleCreateBucketIfNotPresent `json:"createBucketIfNotPresent,omitempty"`
	EncryptionOptions        *PurpleEncryptionOptions        `json:"encryptionOptions,omitempty"`
	Endpoint                 *string                         `json:"endpoint,omitempty"`
	Insecure                 *bool                           `json:"insecure,omitempty"`
	Key                      *string                         `json:"key,omitempty"`
	Region                   *string                         `json:"region,omitempty"`
	RoleARN                  *string                         `json:"roleARN,omitempty"`
	SecretKeySecret          *FluffySecretKeySecret          `json:"secretKeySecret,omitempty"`
	SessionTokenSecret       *PurpleSessionTokenSecret       `json:"sessionTokenSecret,omitempty"`
	UseSDKCreds              *bool                           `json:"useSDKCreds,omitempty"`
}

type FluffyAccessKeySecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type PurpleCASecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type PurpleCreateBucketIfNotPresent struct {
	ObjectLocking *bool `json:"objectLocking,omitempty"`
}

type PurpleEncryptionOptions struct {
	EnableEncryption            *bool                              `json:"enableEncryption,omitempty"`
	KmsEncryptionContext        *string                            `json:"kmsEncryptionContext,omitempty"`
	KmsKeyID                    *string                            `json:"kmsKeyId,omitempty"`
	ServerSideCustomerKeySecret *PurpleServerSideCustomerKeySecret `json:"serverSideCustomerKeySecret,omitempty"`
}

type PurpleServerSideCustomerKeySecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type FluffySecretKeySecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type PurpleSessionTokenSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type Artifact struct {
	Archive        *Archive             `json:"archive,omitempty"`
	ArchiveLogs    *bool                `json:"archiveLogs,omitempty"`
	ArtifactGC     *ArtifactGC          `json:"artifactGC,omitempty"`
	Artifactory    *ArtifactArtifactory `json:"artifactory,omitempty"`
	Azure          *ArtifactAzure       `json:"azure,omitempty"`
	Deleted        *bool                `json:"deleted,omitempty"`
	From           *string              `json:"from,omitempty"`
	FromExpression *string              `json:"fromExpression,omitempty"`
	Gcs            *ArtifactGcs         `json:"gcs,omitempty"`
	Git            *ArtifactGit         `json:"git,omitempty"`
	GlobalName     *string              `json:"globalName,omitempty"`
	Hdfs           *ArtifactHdfs        `json:"hdfs,omitempty"`
	HTTP           *ArtifactHTTP        `json:"http,omitempty"`
	Mode           *int64               `json:"mode,omitempty"`
	Name           string               `json:"name"`
	Optional       *bool                `json:"optional,omitempty"`
	OSS            *ArtifactOSS         `json:"oss,omitempty"`
	Path           *string              `json:"path,omitempty"`
	Plugin         *ArtifactPlugin      `json:"plugin,omitempty"`
	Raw            *ArtifactRaw         `json:"raw,omitempty"`
	RecurseMode    *bool                `json:"recurseMode,omitempty"`
	S3             *ArtifactS3          `json:"s3,omitempty"`
	SubPath        *string              `json:"subPath,omitempty"`
}

type Archive struct {
	None map[string]interface{} `json:"none,omitempty"`
	Tar  *Tar                   `json:"tar,omitempty"`
	Zip  map[string]interface{} `json:"zip,omitempty"`
}

type Tar struct {
	CompressionLevel *int64 `json:"compressionLevel,omitempty"`
}

type ArtifactGC struct {
	PodMetadata        *PodMetadata `json:"podMetadata,omitempty"`
	ServiceAccountName *string      `json:"serviceAccountName,omitempty"`
	Strategy           *Strategy    `json:"strategy,omitempty"`
}

type PodMetadata struct {
	Annotations map[string]string `json:"annotations,omitempty"`
	Labels      map[string]string `json:"labels,omitempty"`
}

type ArtifactArtifactory struct {
	PasswordSecret *StickyPasswordSecret `json:"passwordSecret,omitempty"`
	URL            string                `json:"url"`
	UsernameSecret *StickyUsernameSecret `json:"usernameSecret,omitempty"`
}

type StickyPasswordSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type StickyUsernameSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type ArtifactAzure struct {
	AccountKeySecret *FluffyAccountKeySecret `json:"accountKeySecret,omitempty"`
	Blob             string                  `json:"blob"`
	Container        string                  `json:"container"`
	Endpoint         string                  `json:"endpoint"`
	UseSDKCreds      *bool                   `json:"useSDKCreds,omitempty"`
}

type FluffyAccountKeySecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type ArtifactGcs struct {
	Bucket                  *string                        `json:"bucket,omitempty"`
	Key                     string                         `json:"key"`
	ServiceAccountKeySecret *FluffyServiceAccountKeySecret `json:"serviceAccountKeySecret,omitempty"`
}

type FluffyServiceAccountKeySecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type ArtifactGit struct {
	Branch                *string                    `json:"branch,omitempty"`
	Depth                 *int64                     `json:"depth,omitempty"`
	DisableSubmodules     *bool                      `json:"disableSubmodules,omitempty"`
	Fetch                 []string                   `json:"fetch,omitempty"`
	InsecureIgnoreHostKey *bool                      `json:"insecureIgnoreHostKey,omitempty"`
	InsecureSkipTLS       *bool                      `json:"insecureSkipTLS,omitempty"`
	PasswordSecret        *IndigoPasswordSecret      `json:"passwordSecret,omitempty"`
	Repo                  string                     `json:"repo"`
	Revision              *string                    `json:"revision,omitempty"`
	SingleBranch          *bool                      `json:"singleBranch,omitempty"`
	SSHPrivateKeySecret   *FluffySSHPrivateKeySecret `json:"sshPrivateKeySecret,omitempty"`
	UsernameSecret        *IndigoUsernameSecret      `json:"usernameSecret,omitempty"`
}

type IndigoPasswordSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type FluffySSHPrivateKeySecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type IndigoUsernameSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type ArtifactHTTP struct {
	Auth    *FluffyAuth    `json:"auth,omitempty"`
	Headers []FluffyHeader `json:"headers,omitempty"`
	URL     string         `json:"url"`
}

type FluffyAuth struct {
	BasicAuth  *FluffyBasicAuth  `json:"basicAuth,omitempty"`
	ClientCERT *FluffyClientCERT `json:"clientCert,omitempty"`
	Oauth2     *FluffyOauth2     `json:"oauth2,omitempty"`
}

type FluffyBasicAuth struct {
	PasswordSecret *IndecentPasswordSecret `json:"passwordSecret,omitempty"`
	UsernameSecret *IndecentUsernameSecret `json:"usernameSecret,omitempty"`
}

type IndecentPasswordSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type IndecentUsernameSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type FluffyClientCERT struct {
	ClientCERTSecret *FluffyClientCERTSecret `json:"clientCertSecret,omitempty"`
	ClientKeySecret  *FluffyClientKeySecret  `json:"clientKeySecret,omitempty"`
}

type FluffyClientCERTSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type FluffyClientKeySecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type FluffyOauth2 struct {
	ClientIDSecret     *FluffyClientIDSecret     `json:"clientIDSecret,omitempty"`
	ClientSecretSecret *FluffyClientSecretSecret `json:"clientSecretSecret,omitempty"`
	EndpointParams     []FluffyEndpointParam     `json:"endpointParams,omitempty"`
	Scopes             []string                  `json:"scopes,omitempty"`
	TokenURLSecret     *FluffyTokenURLSecret     `json:"tokenURLSecret,omitempty"`
}

type FluffyClientIDSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type FluffyClientSecretSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type FluffyEndpointParam struct {
	Key   string  `json:"key"`
	Value *string `json:"value,omitempty"`
}

type FluffyTokenURLSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type FluffyHeader struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type ArtifactHdfs struct {
	Addresses               []string                  `json:"addresses,omitempty"`
	DataTransferProtection  *string                   `json:"dataTransferProtection,omitempty"`
	Force                   *bool                     `json:"force,omitempty"`
	HdfsUser                *string                   `json:"hdfsUser,omitempty"`
	KrbCCacheSecret         *FluffyKrbCCacheSecret    `json:"krbCCacheSecret,omitempty"`
	KrbConfigConfigMap      *FluffyKrbConfigConfigMap `json:"krbConfigConfigMap,omitempty"`
	KrbKeytabSecret         *FluffyKrbKeytabSecret    `json:"krbKeytabSecret,omitempty"`
	KrbRealm                *string                   `json:"krbRealm,omitempty"`
	KrbServicePrincipalName *string                   `json:"krbServicePrincipalName,omitempty"`
	KrbUsername             *string                   `json:"krbUsername,omitempty"`
	Path                    string                    `json:"path"`
}

type FluffyKrbCCacheSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type FluffyKrbConfigConfigMap struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type FluffyKrbKeytabSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type ArtifactOSS struct {
	AccessKeySecret          *TentacledAccessKeySecret `json:"accessKeySecret,omitempty"`
	Bucket                   *string                   `json:"bucket,omitempty"`
	CreateBucketIfNotPresent *bool                     `json:"createBucketIfNotPresent,omitempty"`
	Endpoint                 *string                   `json:"endpoint,omitempty"`
	Key                      string                    `json:"key"`
	LifecycleRule            *FluffyLifecycleRule      `json:"lifecycleRule,omitempty"`
	SecretKeySecret          *TentacledSecretKeySecret `json:"secretKeySecret,omitempty"`
	SecurityToken            *string                   `json:"securityToken,omitempty"`
	UseSDKCreds              *bool                     `json:"useSDKCreds,omitempty"`
}

type TentacledAccessKeySecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type FluffyLifecycleRule struct {
	MarkDeletionAfterDays         *int64 `json:"markDeletionAfterDays,omitempty"`
	MarkInfrequentAccessAfterDays *int64 `json:"markInfrequentAccessAfterDays,omitempty"`
}

type TentacledSecretKeySecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type ArtifactPlugin struct {
	Configuration            *string `json:"configuration,omitempty"`
	ConnectionTimeoutSeconds *int64  `json:"connectionTimeoutSeconds,omitempty"`
	Key                      string  `json:"key"`
	Name                     *string `json:"name,omitempty"`
}

type ArtifactRaw struct {
	Data string `json:"data"`
}

type ArtifactS3 struct {
	AccessKeySecret          *StickyAccessKeySecret          `json:"accessKeySecret,omitempty"`
	Bucket                   *string                         `json:"bucket,omitempty"`
	CASecret                 *FluffyCASecret                 `json:"caSecret,omitempty"`
	CreateBucketIfNotPresent *FluffyCreateBucketIfNotPresent `json:"createBucketIfNotPresent,omitempty"`
	EncryptionOptions        *FluffyEncryptionOptions        `json:"encryptionOptions,omitempty"`
	Endpoint                 *string                         `json:"endpoint,omitempty"`
	Insecure                 *bool                           `json:"insecure,omitempty"`
	Key                      *string                         `json:"key,omitempty"`
	Region                   *string                         `json:"region,omitempty"`
	RoleARN                  *string                         `json:"roleARN,omitempty"`
	SecretKeySecret          *StickySecretKeySecret          `json:"secretKeySecret,omitempty"`
	SessionTokenSecret       *FluffySessionTokenSecret       `json:"sessionTokenSecret,omitempty"`
	UseSDKCreds              *bool                           `json:"useSDKCreds,omitempty"`
}

type StickyAccessKeySecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type FluffyCASecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type FluffyCreateBucketIfNotPresent struct {
	ObjectLocking *bool `json:"objectLocking,omitempty"`
}

type FluffyEncryptionOptions struct {
	EnableEncryption            *bool                              `json:"enableEncryption,omitempty"`
	KmsEncryptionContext        *string                            `json:"kmsEncryptionContext,omitempty"`
	KmsKeyID                    *string                            `json:"kmsKeyId,omitempty"`
	ServerSideCustomerKeySecret *FluffyServerSideCustomerKeySecret `json:"serverSideCustomerKeySecret,omitempty"`
}

type FluffyServerSideCustomerKeySecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type StickySecretKeySecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

type FluffySessionTokenSecret struct {
	Key      string  `json:"key"`
	Name     *string `json:"name,omitempty"`
	Optional *bool   `json:"optional,omitempty"`
}

// ArtifactGCStatus describes the result of the deletion
type Status struct {
	// ArtifactResultsByNode maps Node name to result
	ArtifactResultsByNode map[string]ArtifactResultsByNode `json:"artifactResultsByNode,omitempty"`
}

// ArtifactResultNodeStatus describes the result of the deletion on a given node
type ArtifactResultsByNode struct {
	// ArtifactResults maps Artifact name to result of the deletion
	ArtifactResults map[string]ArtifactResult `json:"artifactResults,omitempty"`
}

// ArtifactResult describes the result of attempting to delete a given Artifact
type ArtifactResult struct {
	// Error is an optional error message which should be set if Success==false
	Error *string `json:"error,omitempty"`
	// Name is the name of the Artifact
	Name string `json:"name"`
	// Success describes whether the deletion succeeded
	Success *bool `json:"success,omitempty"`
}

type Strategy string

const (
	Empty                Strategy = ""
	Never                Strategy = "Never"
	OnWorkflowCompletion Strategy = "OnWorkflowCompletion"
	OnWorkflowDeletion   Strategy = "OnWorkflowDeletion"
)
