// Code generated by gen-api-types. DO NOT EDIT.
package workfloweventbinding

// WorkflowEventBinding is the definition of an event resource
type Types struct {
	// APIVersion defines the versioned schema of this representation of an object.
	// Servers should convert recognized schemas to the latest internal value, and
	// may reject unrecognized values.
	// More info:
	// https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	APIVersion *string `json:"apiVersion,omitempty"`
	// Kind is a string value representing the REST resource this object represents.
	// Servers may infer this from the endpoint the client submits requests to.
	// Cannot be updated.
	// In CamelCase.
	// More info:
	// https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind     *string                `json:"kind,omitempty"`
	Metadata map[string]interface{} `json:"metadata"`
	Spec     Spec                   `json:"spec"`
}

type Spec struct {
	// Event is the event to bind to
	Event Event `json:"event"`
	// Submit is the workflow template to submit
	Submit *Submit `json:"submit,omitempty"`
}

// Event is the event to bind to
type Event struct {
	// Selector (https://github.com/expr-lang/expr) that we must must match the event. E.g.
	// `payload.message == "test"`
	Selector string `json:"selector"`
}

// Submit is the workflow template to submit
type Submit struct {
	// Arguments extracted from the event and then set as arguments to the workflow created.
	Arguments *Arguments `json:"arguments,omitempty"`
	// Metadata optional means to customize select fields of the workflow metadata
	Metadata *Metadata `json:"metadata,omitempty"`
	// WorkflowTemplateRef the workflow template to submit
	WorkflowTemplateRef WorkflowTemplateRef `json:"workflowTemplateRef"`
}

// Arguments extracted from the event and then set as arguments to the workflow created.
type Arguments struct {
	// Artifacts is the list of artifacts to pass to the template or workflow
	Artifacts []Artifact `json:"artifacts,omitempty"`
	// Parameters is the list of parameters to pass to the template or workflow
	Parameters []Parameter `json:"parameters,omitempty"`
}

// Artifact indicates an artifact to place at a specified path
type Artifact struct {
	// Archive controls how the artifact will be saved to the artifact repository.
	Archive *Archive `json:"archive,omitempty"`
	// ArchiveLogs indicates if the container logs should be archived
	ArchiveLogs *bool `json:"archiveLogs,omitempty"`
	// ArtifactGC describes the strategy to use when to deleting an artifact from completed or
	// deleted workflows
	ArtifactGC *ArtifactGC `json:"artifactGC,omitempty"`
	// Artifactory contains artifactory artifact location details
	Artifactory *Artifactory `json:"artifactory,omitempty"`
	// Azure contains Azure Storage artifact location details
	Azure *Azure `json:"azure,omitempty"`
	// Has this been deleted?
	Deleted *bool `json:"deleted,omitempty"`
	// From allows an artifact to reference an artifact from a previous step
	From *string `json:"from,omitempty"`
	// FromExpression, if defined, is evaluated to specify the value for the artifact
	FromExpression *string `json:"fromExpression,omitempty"`
	// GCS contains GCS artifact location details
	Gcs *Gcs `json:"gcs,omitempty"`
	// Git contains git artifact location details
	Git *Git `json:"git,omitempty"`
	// GlobalName exports an output artifact to the global scope, making it available as
	// '{{workflow.outputs.artifacts.XXXX}} and in workflow.status.outputs.artifacts
	GlobalName *string `json:"globalName,omitempty"`
	// HDFS contains HDFS artifact location details
	Hdfs *Hdfs `json:"hdfs,omitempty"`
	// HTTP contains HTTP artifact location details
	HTTP *HTTP `json:"http,omitempty"`
	// mode bits to use on this file, must be a value between 0 and 0777.
	// Set when loading input artifacts. It is recommended to set the mode value
	// to ensure the artifact has the expected permissions in your container.
	Mode *int64 `json:"mode,omitempty"`
	// name of the artifact. must be unique within a template's inputs/outputs.
	Name string `json:"name"`
	// Make Artifacts optional, if Artifacts doesn't generate or exist
	Optional *bool `json:"optional,omitempty"`
	// OSS contains OSS artifact location details
	OSS *OSS `json:"oss,omitempty"`
	// Path is the container path to the artifact
	Path *string `json:"path,omitempty"`
	// Plugin contains plugin artifact location details
	Plugin *Plugin `json:"plugin,omitempty"`
	// Raw contains raw artifact location details
	Raw *Raw `json:"raw,omitempty"`
	// If mode is set, apply the permission recursively into the artifact if it is a folder
	RecurseMode *bool `json:"recurseMode,omitempty"`
	// S3 contains S3 artifact location details
	S3 *S3 `json:"s3,omitempty"`
	// SubPath allows an artifact to be sourced from a subpath within the specified source
	SubPath *string `json:"subPath,omitempty"`
}

// Archive controls how the artifact will be saved to the artifact repository.
type Archive struct {
	// NoneStrategy indicates to skip tar process and upload the files or directory tree as
	// independent
	// files. Note that if the artifact is a directory, the artifact driver must support the
	// ability to
	// save/load the directory appropriately.
	None map[string]interface{} `json:"none,omitempty"`
	// TarStrategy will tar and gzip the file or directory when saving
	Tar *Tar `json:"tar,omitempty"`
	// ZipStrategy will unzip zipped input artifacts
	Zip map[string]interface{} `json:"zip,omitempty"`
}

// TarStrategy will tar and gzip the file or directory when saving
type Tar struct {
	// CompressionLevel specifies the gzip compression level to use for the artifact.
	// Defaults to gzip.DefaultCompression.
	CompressionLevel *int64 `json:"compressionLevel,omitempty"`
}

// ArtifactGC describes the strategy to use when to deleting an artifact from completed or
// deleted workflows
type ArtifactGC struct {
	// PodMetadata is an optional field for specifying the Labels and Annotations that should be
	// assigned to the Pod doing the deletion
	PodMetadata *PodMetadata `json:"podMetadata,omitempty"`
	// ServiceAccountName is an optional field for specifying the Service Account that should be
	// assigned to the Pod doing the deletion
	ServiceAccountName *string `json:"serviceAccountName,omitempty"`
	// Strategy is the strategy to use.
	Strategy *Strategy `json:"strategy,omitempty"`
}

// PodMetadata is an optional field for specifying the Labels and Annotations that should be
// assigned to the Pod doing the deletion
type PodMetadata struct {
	Annotations map[string]string `json:"annotations,omitempty"`
	Labels      map[string]string `json:"labels,omitempty"`
}

// Artifactory contains artifactory artifact location details
type Artifactory struct {
	// PasswordSecret is the secret selector to the repository password
	PasswordSecret *ArtifactoryPasswordSecret `json:"passwordSecret,omitempty"`
	// URL of the artifact
	URL string `json:"url"`
	// UsernameSecret is the secret selector to the repository username
	UsernameSecret *ArtifactoryUsernameSecret `json:"usernameSecret,omitempty"`
}

// PasswordSecret is the secret selector to the repository password
type ArtifactoryPasswordSecret struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// UsernameSecret is the secret selector to the repository username
type ArtifactoryUsernameSecret struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// Azure contains Azure Storage artifact location details
type Azure struct {
	// AccountKeySecret is the secret selector to the Azure Blob Storage account access key
	AccountKeySecret *AccountKeySecret `json:"accountKeySecret,omitempty"`
	// Blob is the blob name (i.e., path) in the container where the artifact resides
	Blob string `json:"blob"`
	// Container is the container where resources will be stored
	Container string `json:"container"`
	// Endpoint is the service url associated with an account. It is most likely
	// "https://<ACCOUNT_NAME>.blob.core.windows.net"
	Endpoint string `json:"endpoint"`
	// UseSDKCreds tells the driver to figure out credentials based on sdk defaults.
	UseSDKCreds *bool `json:"useSDKCreds,omitempty"`
}

// AccountKeySecret is the secret selector to the Azure Blob Storage account access key
type AccountKeySecret struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// GCS contains GCS artifact location details
type Gcs struct {
	// Bucket is the name of the bucket
	Bucket *string `json:"bucket,omitempty"`
	// Key is the path in the bucket where the artifact resides
	Key string `json:"key"`
	// ServiceAccountKeySecret is the secret selector to the bucket's service account key
	ServiceAccountKeySecret *ServiceAccountKeySecret `json:"serviceAccountKeySecret,omitempty"`
}

// ServiceAccountKeySecret is the secret selector to the bucket's service account key
type ServiceAccountKeySecret struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// Git contains git artifact location details
type Git struct {
	// Branch is the branch to fetch when `SingleBranch` is enabled
	Branch *string `json:"branch,omitempty"`
	// Depth specifies clones/fetches should be shallow and include the given
	// number of commits from the branch tip
	Depth *int64 `json:"depth,omitempty"`
	// DisableSubmodules disables submodules during git clone
	DisableSubmodules *bool `json:"disableSubmodules,omitempty"`
	// Fetch specifies a number of refs that should be fetched before checkout
	Fetch []string `json:"fetch,omitempty"`
	// InsecureIgnoreHostKey disables SSH strict host key checking during git clone
	InsecureIgnoreHostKey *bool `json:"insecureIgnoreHostKey,omitempty"`
	// InsecureSkipTLS disables server certificate verification resulting in insecure HTTPS
	// connections
	InsecureSkipTLS *bool `json:"insecureSkipTLS,omitempty"`
	// PasswordSecret is the secret selector to the repository password
	PasswordSecret *GitPasswordSecret `json:"passwordSecret,omitempty"`
	// Repo is the git repository
	Repo string `json:"repo"`
	// Revision is the git commit, tag, branch to checkout
	Revision *string `json:"revision,omitempty"`
	// SingleBranch enables single branch clone, using the `branch` parameter
	SingleBranch *bool `json:"singleBranch,omitempty"`
	// SSHPrivateKeySecret is the secret selector to the repository ssh private key
	SSHPrivateKeySecret *SSHPrivateKeySecret `json:"sshPrivateKeySecret,omitempty"`
	// UsernameSecret is the secret selector to the repository username
	UsernameSecret *GitUsernameSecret `json:"usernameSecret,omitempty"`
}

// PasswordSecret is the secret selector to the repository password
type GitPasswordSecret struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// SSHPrivateKeySecret is the secret selector to the repository ssh private key
type SSHPrivateKeySecret struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// UsernameSecret is the secret selector to the repository username
type GitUsernameSecret struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// HTTP contains HTTP artifact location details
type HTTP struct {
	// Auth contains information for client authentication
	Auth *Auth `json:"auth,omitempty"`
	// Headers are an optional list of headers to send with HTTP requests for artifacts
	Headers []Header `json:"headers,omitempty"`
	// URL of the artifact
	URL string `json:"url"`
}

// Auth contains information for client authentication
type Auth struct {
	// BasicAuth describes the secret selectors required for basic authentication
	BasicAuth *BasicAuth `json:"basicAuth,omitempty"`
	// ClientCertAuth holds necessary information for client authentication via certificates
	ClientCERT *ClientCERT `json:"clientCert,omitempty"`
	// OAuth2Auth holds all information for client authentication via OAuth2 tokens
	Oauth2 *Oauth2 `json:"oauth2,omitempty"`
}

// BasicAuth describes the secret selectors required for basic authentication
type BasicAuth struct {
	// PasswordSecret is the secret selector to the repository password
	PasswordSecret *BasicAuthPasswordSecret `json:"passwordSecret,omitempty"`
	// UsernameSecret is the secret selector to the repository username
	UsernameSecret *BasicAuthUsernameSecret `json:"usernameSecret,omitempty"`
}

// PasswordSecret is the secret selector to the repository password
type BasicAuthPasswordSecret struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// UsernameSecret is the secret selector to the repository username
type BasicAuthUsernameSecret struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// ClientCertAuth holds necessary information for client authentication via certificates
type ClientCERT struct {
	// SecretKeySelector selects a key of a Secret.
	ClientCERTSecret *ClientCERTSecret `json:"clientCertSecret,omitempty"`
	// SecretKeySelector selects a key of a Secret.
	ClientKeySecret *ClientKeySecret `json:"clientKeySecret,omitempty"`
}

// SecretKeySelector selects a key of a Secret.
type ClientCERTSecret struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// SecretKeySelector selects a key of a Secret.
type ClientKeySecret struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// OAuth2Auth holds all information for client authentication via OAuth2 tokens
type Oauth2 struct {
	// SecretKeySelector selects a key of a Secret.
	ClientIDSecret *ClientIDSecret `json:"clientIDSecret,omitempty"`
	// SecretKeySelector selects a key of a Secret.
	ClientSecretSecret *ClientSecretSecret `json:"clientSecretSecret,omitempty"`
	EndpointParams     []EndpointParam     `json:"endpointParams,omitempty"`
	Scopes             []string            `json:"scopes,omitempty"`
	// SecretKeySelector selects a key of a Secret.
	TokenURLSecret *TokenURLSecret `json:"tokenURLSecret,omitempty"`
}

// SecretKeySelector selects a key of a Secret.
type ClientIDSecret struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// SecretKeySelector selects a key of a Secret.
type ClientSecretSecret struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// EndpointParam is for requesting optional fields that should be sent in the oauth request
type EndpointParam struct {
	// Name is the header name
	Key string `json:"key"`
	// Value is the literal value to use for the header
	Value *string `json:"value,omitempty"`
}

// SecretKeySelector selects a key of a Secret.
type TokenURLSecret struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// Header indicate a key-value request header to be used when fetching artifacts over HTTP
type Header struct {
	// Name is the header name
	Name string `json:"name"`
	// Value is the literal value to use for the header
	Value string `json:"value"`
}

// HDFS contains HDFS artifact location details
type Hdfs struct {
	// Addresses is accessible addresses of HDFS name nodes
	Addresses []string `json:"addresses,omitempty"`
	// DataTransferProtection is the protection level for HDFS data transfer.
	// It corresponds to the dfs.data.transfer.protection configuration in HDFS.
	DataTransferProtection *string `json:"dataTransferProtection,omitempty"`
	// Force copies a file forcibly even if it exists
	Force *bool `json:"force,omitempty"`
	// HDFSUser is the user to access HDFS file system.
	// It is ignored if either ccache or keytab is used.
	HdfsUser *string `json:"hdfsUser,omitempty"`
	// KrbCCacheSecret is the secret selector for Kerberos ccache
	// Either ccache or keytab can be set to use Kerberos.
	KrbCCacheSecret *KrbCCacheSecret `json:"krbCCacheSecret,omitempty"`
	// KrbConfig is the configmap selector for Kerberos config as string
	// It must be set if either ccache or keytab is used.
	KrbConfigConfigMap *KrbConfigConfigMap `json:"krbConfigConfigMap,omitempty"`
	// KrbKeytabSecret is the secret selector for Kerberos keytab
	// Either ccache or keytab can be set to use Kerberos.
	KrbKeytabSecret *KrbKeytabSecret `json:"krbKeytabSecret,omitempty"`
	// KrbRealm is the Kerberos realm used with Kerberos keytab
	// It must be set if keytab is used.
	KrbRealm *string `json:"krbRealm,omitempty"`
	// KrbServicePrincipalName is the principal name of Kerberos service
	// It must be set if either ccache or keytab is used.
	KrbServicePrincipalName *string `json:"krbServicePrincipalName,omitempty"`
	// KrbUsername is the Kerberos username used with Kerberos keytab
	// It must be set if keytab is used.
	KrbUsername *string `json:"krbUsername,omitempty"`
	// Path is a file path in HDFS
	Path string `json:"path"`
}

// KrbCCacheSecret is the secret selector for Kerberos ccache
// Either ccache or keytab can be set to use Kerberos.
type KrbCCacheSecret struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// KrbConfig is the configmap selector for Kerberos config as string
// It must be set if either ccache or keytab is used.
type KrbConfigConfigMap struct {
	// The key to select.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the ConfigMap or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// KrbKeytabSecret is the secret selector for Kerberos keytab
// Either ccache or keytab can be set to use Kerberos.
type KrbKeytabSecret struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// OSS contains OSS artifact location details
type OSS struct {
	// AccessKeySecret is the secret selector to the bucket's access key
	AccessKeySecret *OSSAccessKeySecret `json:"accessKeySecret,omitempty"`
	// Bucket is the name of the bucket
	Bucket *string `json:"bucket,omitempty"`
	// CreateBucketIfNotPresent tells the driver to attempt to create the OSS bucket for output
	// artifacts, if it doesn't exist
	CreateBucketIfNotPresent *bool `json:"createBucketIfNotPresent,omitempty"`
	// Endpoint is the hostname of the bucket endpoint
	Endpoint *string `json:"endpoint,omitempty"`
	// Key is the path in the bucket where the artifact resides
	Key string `json:"key"`
	// LifecycleRule specifies how to manage bucket's lifecycle
	LifecycleRule *LifecycleRule `json:"lifecycleRule,omitempty"`
	// SecretKeySecret is the secret selector to the bucket's secret key
	SecretKeySecret *OSSSecretKeySecret `json:"secretKeySecret,omitempty"`
	// SecurityToken is the user's temporary security token. For more details, check out:
	// https://www.alibabacloud.com/help/doc-detail/100624.htm
	SecurityToken *string `json:"securityToken,omitempty"`
	// UseSDKCreds tells the driver to figure out credentials based on sdk defaults.
	UseSDKCreds *bool `json:"useSDKCreds,omitempty"`
}

// AccessKeySecret is the secret selector to the bucket's access key
type OSSAccessKeySecret struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// LifecycleRule specifies how to manage bucket's lifecycle
type LifecycleRule struct {
	// MarkDeletionAfterDays is the number of days before we delete objects in the bucket
	MarkDeletionAfterDays *int64 `json:"markDeletionAfterDays,omitempty"`
	// MarkInfrequentAccessAfterDays is the number of days before we convert the objects in the
	// bucket to Infrequent Access (IA) storage type
	MarkInfrequentAccessAfterDays *int64 `json:"markInfrequentAccessAfterDays,omitempty"`
}

// SecretKeySecret is the secret selector to the bucket's secret key
type OSSSecretKeySecret struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// Plugin contains plugin artifact location details
type Plugin struct {
	// Configuration is the plugin defined configuration for the artifact driver plugin
	Configuration *string `json:"configuration,omitempty"`
	// ConnectionTimeoutSeconds is the timeout for the artifact driver connection, overriding
	// the driver's timeout
	ConnectionTimeoutSeconds *int64 `json:"connectionTimeoutSeconds,omitempty"`
	// Key is the path in the artifact repository where the artifact resides
	Key string `json:"key"`
	// Name is the name of the artifact driver plugin
	Name *string `json:"name,omitempty"`
}

// Raw contains raw artifact location details
type Raw struct {
	// Data is the string contents of the artifact
	Data string `json:"data"`
}

// S3 contains S3 artifact location details
type S3 struct {
	// AccessKeySecret is the secret selector to the bucket's access key
	AccessKeySecret *S3AccessKeySecret `json:"accessKeySecret,omitempty"`
	// Bucket is the name of the bucket
	Bucket *string `json:"bucket,omitempty"`
	// CASecret specifies the secret that contains the CA, used to verify the TLS connection
	CASecret *CASecret `json:"caSecret,omitempty"`
	// CreateBucketIfNotPresent tells the driver to attempt to create the S3 bucket for output
	// artifacts, if it doesn't exist. Setting Enabled Encryption will apply either SSE-S3 to
	// the bucket if KmsKeyId is not set or SSE-KMS if it is.
	CreateBucketIfNotPresent *CreateBucketIfNotPresent `json:"createBucketIfNotPresent,omitempty"`
	// S3EncryptionOptions used to determine encryption options during s3 operations
	EncryptionOptions *EncryptionOptions `json:"encryptionOptions,omitempty"`
	// Endpoint is the hostname of the bucket endpoint
	Endpoint *string `json:"endpoint,omitempty"`
	// Insecure will connect to the service with TLS
	Insecure *bool `json:"insecure,omitempty"`
	// Key is the key in the bucket where the artifact resides
	Key *string `json:"key,omitempty"`
	// Region contains the optional bucket region
	Region *string `json:"region,omitempty"`
	// RoleARN is the Amazon Resource Name (ARN) of the role to assume.
	RoleARN *string `json:"roleARN,omitempty"`
	// SecretKeySecret is the secret selector to the bucket's secret key
	SecretKeySecret *S3SecretKeySecret `json:"secretKeySecret,omitempty"`
	// SessionTokenSecret is used for ephemeral credentials like an IAM assume role or S3 access
	// grant
	SessionTokenSecret *SessionTokenSecret `json:"sessionTokenSecret,omitempty"`
	// UseSDKCreds tells the driver to figure out credentials based on sdk defaults.
	UseSDKCreds *bool `json:"useSDKCreds,omitempty"`
}

// AccessKeySecret is the secret selector to the bucket's access key
type S3AccessKeySecret struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// CASecret specifies the secret that contains the CA, used to verify the TLS connection
type CASecret struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// CreateBucketIfNotPresent tells the driver to attempt to create the S3 bucket for output
// artifacts, if it doesn't exist. Setting Enabled Encryption will apply either SSE-S3 to
// the bucket if KmsKeyId is not set or SSE-KMS if it is.
type CreateBucketIfNotPresent struct {
	// ObjectLocking Enable object locking
	ObjectLocking *bool `json:"objectLocking,omitempty"`
}

// S3EncryptionOptions used to determine encryption options during s3 operations
type EncryptionOptions struct {
	// EnableEncryption tells the driver to encrypt objects if set to true. If kmsKeyId and
	// serverSideCustomerKeySecret are not set, SSE-S3 will be used
	EnableEncryption *bool `json:"enableEncryption,omitempty"`
	// KmsEncryptionContext is a json blob that contains an encryption context. See
	// https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#encrypt_context for
	// more information
	KmsEncryptionContext *string `json:"kmsEncryptionContext,omitempty"`
	// KMSKeyId tells the driver to encrypt the object using the specified KMS Key.
	KmsKeyID *string `json:"kmsKeyId,omitempty"`
	// ServerSideCustomerKeySecret tells the driver to encrypt the output artifacts using SSE-C
	// with the specified secret.
	ServerSideCustomerKeySecret *ServerSideCustomerKeySecret `json:"serverSideCustomerKeySecret,omitempty"`
}

// ServerSideCustomerKeySecret tells the driver to encrypt the output artifacts using SSE-C
// with the specified secret.
type ServerSideCustomerKeySecret struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// SecretKeySecret is the secret selector to the bucket's secret key
type S3SecretKeySecret struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// SessionTokenSecret is used for ephemeral credentials like an IAM assume role or S3 access
// grant
type SessionTokenSecret struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// Parameter indicate a passed string parameter to a service template with an optional
// default value
type Parameter struct {
	// Default is the default value to use for an input parameter if a value was not supplied
	Default *string `json:"default,omitempty"`
	// Description is the parameter description
	Description *string `json:"description,omitempty"`
	// Enum holds a list of string values to choose from, for the actual value of the parameter
	Enum []string `json:"enum,omitempty"`
	// GlobalName exports an output parameter to the global scope, making it available as
	// '{{workflow.outputs.parameters.XXXX}} and in workflow.status.outputs.parameters
	GlobalName *string `json:"globalName,omitempty"`
	// Name is the parameter name
	Name string `json:"name"`
	// Value is the literal value to use for the parameter.
	// If specified in the context of an input parameter, any passed values take precedence over
	// the specified value
	Value *string `json:"value,omitempty"`
	// ValueFrom is the source for the output parameter's value
	ValueFrom *ValueFrom `json:"valueFrom,omitempty"`
}

// ValueFrom is the source for the output parameter's value
type ValueFrom struct {
	// ConfigMapKeyRef is configmap selector for input parameter configuration
	ConfigMapKeyRef *ConfigMapKeyRef `json:"configMapKeyRef,omitempty"`
	// Default specifies a value to be used if retrieving the value from the specified source
	// fails
	Default *string `json:"default,omitempty"`
	// Selector (https://github.com/expr-lang/expr) that is evaluated against the event to get
	// the value of the parameter. E.g. `payload.message`
	Event *string `json:"event,omitempty"`
	// Expression, if defined, is evaluated to specify the value for the parameter
	Expression *string `json:"expression,omitempty"`
	// JQFilter expression against the resource object in resource templates
	JqFilter *string `json:"jqFilter,omitempty"`
	// JSONPath of a resource to retrieve an output parameter value from in resource templates
	JSONPath *string `json:"jsonPath,omitempty"`
	// Parameter reference to a step or dag task in which to retrieve an output parameter value
	// from
	// (e.g. '{{steps.mystep.outputs.myparam}}')
	Parameter *string `json:"parameter,omitempty"`
	// Path in the container to retrieve an output parameter value from in container templates
	Path *string `json:"path,omitempty"`
	// Supplied value to be filled in directly, either through the CLI, API, etc.
	Supplied map[string]interface{} `json:"supplied,omitempty"`
}

// ConfigMapKeyRef is configmap selector for input parameter configuration
type ConfigMapKeyRef struct {
	// The key to select.
	Key string `json:"key"`
	// Name of the referent.
	// This field is effectively required, but due to backwards compatibility is
	// allowed to be empty. Instances of this type with an empty value here are
	// almost certainly wrong.
	// More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the ConfigMap or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// Metadata optional means to customize select fields of the workflow metadata
type Metadata struct {
	Annotations  map[string]string `json:"annotations,omitempty"`
	Finalizers   []string          `json:"finalizers,omitempty"`
	GenerateName *string           `json:"generateName,omitempty"`
	Labels       map[string]string `json:"labels,omitempty"`
	Name         *string           `json:"name,omitempty"`
	Namespace    *string           `json:"namespace,omitempty"`
}

// WorkflowTemplateRef the workflow template to submit
type WorkflowTemplateRef struct {
	// ClusterScope indicates the referred template is cluster scoped (i.e. a
	// ClusterWorkflowTemplate).
	ClusterScope *bool `json:"clusterScope,omitempty"`
	// Name is the resource name of the workflow template.
	Name *string `json:"name,omitempty"`
}

// Strategy is the strategy to use.
type Strategy string

const (
	Empty                Strategy = ""
	Never                Strategy = "Never"
	OnWorkflowCompletion Strategy = "OnWorkflowCompletion"
	OnWorkflowDeletion   Strategy = "OnWorkflowDeletion"
)
