#!/usr/bin/env python3
import glob
import json
import os
import subprocess
import sys
import tempfile
import yaml

def main():
    root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    crds_dir = os.path.join(root_dir, 'api', 'crds')
    openapi_out = os.path.join(root_dir, 'api', 'openapi.json')
    ts_out = os.path.join(root_dir, 'frontend', 'src', 'types', 'generated.ts')
    go_out = os.path.join(root_dir, 'internal', 'api', 'types.go')

    if not os.path.exists(crds_dir):
        print(f"Error: CRDs directory not found at {crds_dir}")
        sys.exit(1)

    crd_files = glob.glob(os.path.join(crds_dir, '*.yaml')) + glob.glob(os.path.join(crds_dir, '*.yml'))
    if not crd_files:
        print(f"Error: No YAML files found in {crds_dir}")
        sys.exit(1)

    schemas = {}
    for fpath in sorted(crd_files):
        with open(fpath, 'r', encoding='utf-8') as f:
            docs = yaml.safe_load_all(f)
            for doc in docs:
                if not doc or doc.get('kind') != 'CustomResourceDefinition':
                    continue
                kind = doc['spec']['names']['kind']
                versions = doc['spec']['versions']
                target_version = next((v for v in versions if v.get('served')), versions[0])
                open_api_schema = target_version['schema']['openAPIV3Schema']
                schemas[kind] = open_api_schema

    openapi_doc = {
        'openapi': '3.0.3',
        'info': {
            'title': 'Argo Workflows Custom Resources',
            'version': 'v1alpha1'
        },
        'paths': {},
        'components': {
            'schemas': schemas
        }
    }

    os.makedirs(os.path.dirname(openapi_out), exist_ok=True)
    with open(openapi_out, 'w', encoding='utf-8') as out:
        json.dump(openapi_doc, out, indent=2)
    print(f"✓ Generated OpenAPI spec at {openapi_out} ({len(schemas)} schemas)")

    # Generate TypeScript types for each resource individually
    generated_ts_dir = os.path.join(root_dir, 'frontend', 'src', 'types', 'generated')
    os.makedirs(generated_ts_dir, exist_ok=True)
    
    # Remove old generated files if they exist
    for f in glob.glob(os.path.join(generated_ts_dir, '*.ts')):
        try:
            os.remove(f)
        except OSError:
            pass
            
    # Also delete the old single generated.ts if it exists
    if os.path.exists(ts_out):
        try:
            os.remove(ts_out)
        except OSError:
            pass

    for kind, schema in schemas.items():
        single_openapi = {
            'openapi': '3.0.3',
            'info': {
                'title': f'Argo Workflows {kind}',
                'version': 'v1alpha1'
            },
            'paths': {},
            'components': {
                'schemas': {
                    kind: schema
                }
            }
        }
        
        with tempfile.NamedTemporaryFile(suffix='.json', mode='w', delete=False, encoding='utf-8') as tmp_openapi:
            json.dump(single_openapi, tmp_openapi, indent=2)
            tmp_openapi_path = tmp_openapi.name
            
        try:
            out_path = os.path.join(generated_ts_dir, f'{kind}.ts')
            ts_cmd = ['npx', '-y', 'openapi-typescript', tmp_openapi_path, '-o', out_path]
            subprocess.run(ts_cmd, check=True, cwd=root_dir)
            print(f"✓ Generated TypeScript types for {kind} at {out_path}")
        finally:
            try:
                os.remove(tmp_openapi_path)
            except OSError:
                pass

    # Generate Go types using quicktype
    os.makedirs(os.path.dirname(go_out), exist_ok=True)
    with tempfile.TemporaryDirectory() as tmpdir:
        schema_paths = []
        for kind, schema in schemas.items():
            p = os.path.join(tmpdir, f'{kind}.json')
            schema_copy = dict(schema)
            schema_copy['$schema'] = 'http://json-schema.org/draft-06/schema#'
            schema_copy['title'] = kind
            with open(p, 'w', encoding='utf-8') as out:
                json.dump(schema_copy, out, indent=2)
            schema_paths.append(p)

        go_cmd = [
            'npx', '-y', 'quicktype',
            '--src-lang', 'schema',
            '--lang', 'go',
            '--package', 'api',
            '--just-types',
            '-o', go_out
        ] + schema_paths
        subprocess.run(go_cmd, check=True, cwd=root_dir)

    # Post-process Go file imports and formatting
    with open(go_out, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    imports = set()
    clean_lines = []
    for line in lines:
        if line.strip().startswith('import '):
            imp = line.strip().replace('import ', '')
            imports.add(imp)
        else:
            clean_lines.append(line)

    if clean_lines and clean_lines[0].startswith('package '):
        clean_lines = clean_lines[1:]

    header = ['// Code generated by gen-api-types. DO NOT EDIT.\npackage api\n\n']
    if imports:
        header.append('import (\n')
        for imp in sorted(imports):
            header.append(f'\t{imp}\n')
        header.append(')\n\n')

    with open(go_out, 'w', encoding='utf-8') as f:
        f.writelines(header + clean_lines)

    subprocess.run(['gofmt', '-w', go_out], check=True, cwd=root_dir)
    print(f"✓ Generated Go types at {go_out}")

if __name__ == '__main__':
    main()
